export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const LOADING_MESSAGES = "LOADING_MESSAGES";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
